### ISSUE TITLE
FYI: Using docker-compose.yml file with redis.

### ISSUE THREAD

**Issue by rquadling** [docker-library/redis#111]
Hi.

I've got redis operational for my application using this snippet in my docker-compose.yml file.

```
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data
    restart: always
```

With this, my stack loads up all fine (nginx, memcached, redis, php-fpm, sockets, mariadb, mailcatcher and data).

If I run `docker logs redis`, I get ...

```
$ docker logs redis
1:C 29 Nov 16:35:46.351 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 29 Nov 16:35:46.352 # Redis version=4.0.2, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 29 Nov 16:35:46.352 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 29 Nov 16:35:46.354 * Running mode=standalone, port=6379.
1:M 29 Nov 16:35:46.354 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 29 Nov 16:35:46.354 # Server initialized
1:M 29 Nov 16:35:46.354 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
1:M 29 Nov 16:35:46.354 * Ready to accept connections
```

With regard to the log entry and THP, https://github.com/docker-library/redis/issues/55 suggests that this is not something to be done within the container, so moving on ...

I can connect to the container and `watch redis-cli --scan` and I see my keys. The application is happy.

Right until I recycle my stack. Then the data is all gone. Makes sense as I've not enabled persistence. So ...

I then found that I can override the entrypoint!

```
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always
```

This is now working as I want.

It may be obvious to some, but the entrypoint was the bit I didn't know initially.

It may be worth adding some of this to the documentation in some form.

**Comment by tianon** [comment]
Something like this? https://github.com/docker-library/docs/blob/55604f7900451290144c0081e7f622297e519f61/redis/README.md#start-with-persistent-storage :wink: 

> ## start with persistent storage
> 
> ```console
> $ docker run --name some-redis -d redis redis-server --appendonly yes
> ```
> 
> If persistence is enabled, data is stored in the `VOLUME /data`, which can be used with `--volumes-from some-volume-container` or `-v /docker/host/dir:/data` (see [docs.docker volumes](https://docs.docker.com/engine/tutorials/dockervolumes/)).
> 
> For more about Redis Persistence, see [http://redis.io/topics/persistence](http://redis.io/topics/persistence).

**Comment by rquadling** [comment]
I don't use docker. I use docker-compose. I start up a whole load of services all in the right order in 1 command. So I have a yaml file. That's the difference. Took me a while to work out what's what.

**Comment by lagden** [comment]
@rquadling

Do you want an example of docker-compose file?

```yaml
version: '3'
services:
  app:
    image: lagden/cep_consulta:5.0.0
    command: ["node", "index.js"]
    environment:
      - NODE_ENV=production
      - RHOST=redis
    ports:
      - 1235:3000
    networks:
      - redis-net
    depends_on:
      - redis

  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - redis-net
    volumes:
      - redis-data:/data

networks:
  redis-net:

volumes:
  redis-data:
```

Useful?

**Comment by tianon** [comment]
> I don't use docker. I use docker-compose.

`docker-compose` is simply a wrapper around `docker` which converts a YAML file into the relevant `docker run` commands in a simple, repeatable way.

Additionally, the example @lagden provided should do the trick (setting `command:`, which matches the appropriate portion of the example `docker run` command from the documentation).

Since this issue appears to be solved, I'm going to close, but feel free to continue the discussion.

**Comment by edsonhoraciojunior** [comment]
@lagden 
 
> ```yaml
> networks:
>   redis-net:
> 
> volumes:
>   redis-data:
> ```

Can you please explain what the top `networks` and `volumes` used like that does?

**Comment by yosifkit** [comment]
@edsonhoraciojunior, they just tell `docker-compose` (or `docker stack`) what networks and volumes to create (and any optional configuration on them).
https://docs.docker.com/compose/compose-file/#network-configuration-reference
https://docs.docker.com/compose/compose-file/#volume-configuration-reference

**Comment by edsonhoraciojunior** [comment]
@yosifkit I wanted to know what it means to leave those blank, and the links you passed explain that, thank you!

**Comment by juandrn** [comment]
You could start with configurqation file 

```
  redis:
    image: redis
    ports:
    - "6379:6379"

    volumes:
    - ~/db/data:/data
    - ~/db/redis.conf:/usr/local/etc/redis/redis.conf

    entrypoint: redis-server /usr/local/etc/redis/redis.conf
```

Examples of configs file:
http://download.redis.io/redis-stable/redis.conf
https://redis.io/topics/config#:~:text=Redis%20is%20able%20to%20start,conf%20.

NOTE: First you need to copy redis.conf in ~/db/redis.conf
- For windows in path %userprofile%/db/redis.conf

**Comment by vald-phoenix** [comment]
Maybe, it's a bit irrelevant but I've never seen this in _docker-compose.yml_ file, so if you want to make use of _/var/lib/redis/dump.rdb_ file i.e. to use keys that you saved to Redis on restart of `docker-compose` then you need to have the following lines in your _docker-compose.yml_ file.

```yml
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
      - redis-dump:/var/lib/redis
```
