### ISSUE TITLE
No matching manifest for linux/amd64

### ISSUE THREAD

**Issue by linstantnoodles** [docker-library/redis#116]
I'm trying to pull and build a redis image using the following docker compose file:
```
version: '2'
services:
  redis:
    container_name: redis
    image: redis
    ports:
      - 6380:6379
```

I run `docker-compose up -d redis` and I get the following output: 

```
Pulling redis (redis:latest)...
latest: Pulling from library/redis
ERROR: no matching manifest for linux/amd64 in the manifest list entries
```

There has been no changes to our compose file or docker since the last time (few weeks ago) we pulled and built this image.
