### ISSUE TITLE
Run server with custom config

### ISSUE THREAD

**Issue by ivanovaleksey** [docker-library/redis#125]
Hello,
I try to run redis server with a custom config via docker compose.

I got the following `docker-compose.yml` file:
```
version: '3'
services:
  web:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - ./log:/app/log
      - ./tmp:/app/tmp
    ports:
      - 9292:9292
    environment:
      - RACK_ENV=production
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
  redis:
    image: redis:alpine
    volumes:
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command:
      - redis-server /usr/local/etc/redis/redis.conf
```

Unfortunately, I got an error:
```
$ docker-compose up
redis_1  | 1:C 04 Feb 21:06:51.504 # Fatal error, can't open config file 'redis-server /usr/local/etc/redis/redis.conf'
redis_1 exited with code 1
web_1    | Puma starting in single mode...
web_1    | * Version 3.11.2 (ruby 2.5.0-p0), codename: Love Song
web_1    | * Min threads: 1, max threads: 1
web_1    | * Environment: production
web_1    | * Listening on tcp://0.0.0.0:9292
web_1    | Use Ctrl-C to stop
```

However, the file does exist. I can run _redis_ service and see it
```$ docker-compose run redis /bin/sh```
```
$ ls -lt /usr/local/etc/redis/redis.conf
-rw-rw-r--    1 1000     1000         57845 Feb  4 20:43 /usr/local/etc/redis/redis.conf
```

It is strange to me that user and group is 1000.
Maybe it causes the issue?
Could you please help to figure it out?

**Comment by yosifkit** [comment]
The ownership of the file would be the cause of the problem (or possibly folder permissions, since `/usr/local/etc/` does not exist and would be created by Docker in making the mount). You have a few options, run the container as your user (`user: '1000:1000'` in your yaml file) which can work because of https://github.com/docker-library/redis/pull/48, or maybe putting the file in a different location in the container would help.

**Comment by ivanovaleksey** [comment]
Thank you for the reply @yosifkit.
I have tried `/usr/local/redis.conf` and `/etc/redis.conf`.
Now it is
```
-rw-r--r--    1 1000     50           57845 Feb  4 20:41 redis.conf
```

Where do these ids came from? Why it isn't `root` or `redis`?

**Comment by tianon** [comment]
Usernames are an abstraction -- the filesystem deals in raw UIDs, so as far as the kernel is concerned, `root` and `redis` don't mean anything.  Those name conversions come from a file located at `/etc/passwd`, which is different on your Docker host system from the one inside the container, which is likely part of the issue you're seeing.  If you don't supply `--user` or `user:` when running the `redis` image, it will step down from root by itself:

https://github.com/docker-library/redis/blob/d53b982b387634092c6f11069401679034054ecb/4.0/docker-entrypoint.sh#L10-L14

As for why you're seeing those specific values, I'd imagine it probably has something to do with your `docker-compose.yml` or your host filesystem.  It sounds like you're probably using Docker Toolbox with boot2docker (since boot2docker uses `1000:50` as the default user for the filesystem share into the Docker VM), but that's just a guess.

Since this isn't really an issue with the image, and is more of a question about usage, I'm going to close. 
 In the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).  Thanks!

**Comment by ivanovaleksey** [comment]
Thanks, I will try to investigate further.

**Comment by ivanovaleksey** [comment]
@tianon @yosifkit 
As it turned out one should command in the following way:
```
redis:
    image: redis:alpine
    volumes:
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command:
      - /usr/local/etc/redis/redis.conf
```

This way `docker-entrypoint.sh` works fine and rewrite the whole command to
```
# set -- redis-server "$@"
redis-server /usr/local/etc/redis/redis.conf
```

In my first message I got error 
```
can't open config file 'redis-server /usr/local/etc/redis/redis.conf'
```
So, the whole command was interpreted as file name.

Now config file was read but I got another error:
```
redis_1  | *** FATAL CONFIG FILE ERROR ***
redis_1  | Reading the configuration file, at line 172
redis_1  | >>> 'logfile /var/log/redis_6379.log'
redis_1  | Can't open the log file: Permission denied
```

**Comment by wolfpack94** [comment]
Any update on this error?

**Comment by yosifkit** [comment]
@wolfpack94, to what error are you referring? The original issue was that the yaml was wrongly configured.


```yaml
# it was this
    command:
      - redis-server /usr/local/etc/redis/redis.conf

# when it should've been this
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf

# or this
    command:
      - /usr/local/etc/redis/redis.conf
```
