### ISSUE TITLE
RDB file set to save in wrong folder

### ISSUE THREAD

**Issue by bitkill** [docker-library/redis#128]
Hi. I have a strange problem with redis. After starting the container, it works ok, but after awhile, it gives me an save error, and blocks my queue service from writing data.
I'm using the redis:latest image. Composing via docker-compose

```
redis:
    image: redis:latest
    volumes:
      - "./redis_data:/data"
    ports:
      - "6379:6379"
    # expose: [ "6379" ]
    networks:
      - redisnw
    restart: always
```

It gives me this error:
```
redis_1           | 1:M 01 Mar 18:45:14.098 * 1 changes in 3600 seconds. Saving...
redis_1           | 1:M 01 Mar 18:45:14.098 * Background saving started by pid 1084
redis_1           | 1084:C 01 Mar 18:45:14.099 # Failed opening the RDB file root (in server root dir /run) for saving: Permission denied
redis_1           | 1:M 01 Mar 18:45:14.199 # Background saving error
```

The strange part is that it tries to save in /run.
There is no configuration provided to save in this folder. Is this a redis default setting?
