### ISSUE TITLE
unable to write to redis.conf, pods crashing

### ISSUE THREAD

**Issue by Justluckyg** [docker-library/redis#134]
I'm trying to deploy redis-sentinel and im using redis:3.0-alpine and currently facing this error.

```
1:X 20 Mar 09:42:31.426 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:X 20 Mar 09:42:31.426 # Sentinel config file /redis-config/redis.conf is not writable: Read-only file system. Exiting...
```

This is on GKE v1.9.4-gke.1

This is the yaml file that were using.

```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: auth-sentinel-redis
  namespace: lenddo
spec:
  replicas: 3
  serviceName: auth-sentinel-redis
  template:
    metadata:
      labels:
        app: auth-sentinel-redis
        redisName: auth
        auth-redis-access: "true"
    spec:
      containers:
      - name: auth-sentinel-redis
        image: redis:3.0-alpine
        #image: quay.io/smile/redis:4.0.8r0
        volumeMounts:
          - name: auth-sentinel-redis
            mountPath: /data
          - name: redis-config
            mountPath: /redis-config
        resources:
          requests:
            cpu: 10m
        ports:
          - name: auth-redis
            containerPort: 26379
            protocol: TCP
        command:
          - redis-server
          - "/redis-config/redis.conf"
          - "--sentinel"
      nodeSelector:
        arbiters: "true"
      volumes:
        - name: redis-config
          configMap:
            name: auth-sentinel-redis-config
            items:
              - key: redis-config
                path: redis.conf
                mode: 420
```
