### ISSUE TITLE
Disabling persistance doesn't work

### ISSUE THREAD

**Issue by MarcusWichelmann** [docker-library/redis#159]
I'm starting the redis-service using docker-compose:
```
service-redis:
    image: redis:latest
    container_name: service-redis
    restart: always
```
So according to the documentation https://hub.docker.com/_/redis/ the persistance mode should be disabled. But when I stop and start the docker-container (without removing it) the data is kept in /data/dump.rdb and restored on restart.

Have I missed any setting to completely disable this persistance or is this a bug?

Kind regards,
Marcus Wichelmann
