### ISSUE TITLE
No prompt

### ISSUE THREAD

**Issue by zanematthew** [docker-library/redis#161]
I have a docker-compose with the following;

```
version: '3'
services:
  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - "./services/redis/data:/data"
```

I can start the service, and connect to it, but I do not see a prompt.

I'm connecting to the service using; `docker-compose exec -T redis bash`, which drops me into a terminal with no prompt, I then can use `redis-cli` and `ping` the redis server and get the `PONG` response, but still no prompt, see below;

```
$ docker-compose exec -T redis bash
redis-cli
ping
PONG
```

<img width="1277" alt="screen shot 2018-08-24 at 8 48 26 am" src="https://user-images.githubusercontent.com/654712/44585494-89876280-a77a-11e8-8fe3-7354b69a9617.png">

I'm currently using Mac OS 10.11.5, using iTerm2 build 3.1.7, but the issue happens with the native Terminal app as well.

Is this an issue with; the redis image? how I'm connecting? related to my local terminal app configuration? I'll also add that this does _not_ happen with other services, I can start a base nginx, or php service and connect to those and those do have a prompt.
