### ISSUE TITLE
How do I set a password for redis?

### ISSUE THREAD

**Issue by ddzyan** [docker-library/redis#176]
```bash
sudo docker run \
> -p 6379:6379 \
> -v $PWD/data:/data \
> --requirepass "__@picker-redis" \
> --name redis \
> -d redis:3.2 redis-server --appendonly yes
unknown flag: --requirepass
See 'docker run --help'.
```

**Comment by tao12345666333** [comment]
You made the wrong position of the parameter.

You should do it, like this:

```
sudo docker run \
> -p 6379:6379 \
> -v $PWD/data:/data \
> --name redis \
> -d redis:3.2 redis-server --appendonly yes  --requirepass "__@picker-redis" 
```

**Comment by ddzyan** [comment]
> You made the wrong position of the parameter.
> 
> You should do it, like this:
> 
> ```
> sudo docker run \
> > -p 6379:6379 \
> > -v $PWD/data:/data \
> > --name redis \
> > -d redis:3.2 redis-server --appendonly yes  --requirepass "__@picker-redis" 
> ```

Thank you, I will try

**Comment by brunowego** [comment]
Sharing this for other users:

## Volume

```sh
docker volume create redis-data
```

## Running

```sh
docker run -d \
  -h redis \
  -e REDIS_PASSWORD=redis \
  -v redis-data:/data \
  -p 6379:6379 \
  --name redis \
  --restart always \
  redis:5.0.5-alpine3.9 /bin/sh -c 'redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}'
```

## Remove

```sh
docker rm -f redis
docker volume rm redis-data
```

**Comment by jrichardsz** [comment]
This worked for me

    docker run --name redis -d -p 6379:6379 redis redis-server --requirepass "SUPER_SECRET_PASSWORD"

**Comment by stevecho-dift** [comment]
> This worked for me
> 
> ```
> docker run --name redis -d -p 6379:6379 redis redis-server --requirepass "SUPER_SECRET_PASSWORD"
> ```



> This worked for me
> 
> ```
> docker run --name redis -d -p 6379:6379 redis redis-server --requirepass "SUPER_SECRET_PASSWORD"
> ```

Thanks mate. It worked for me too!

**Comment by CenkCamkiran** [comment]
> --requirepass

Thanks mate!

**Comment by antonioGabrielGomes** [comment]
> You made the wrong position of the parameter.
> 
> You should do it, like this:
> 
> ```
> sudo docker run \
> > -p 6379:6379 \
> > -v $PWD/data:/data \
> > --name redis \
> > -d redis:3.2 redis-server --appendonly yes  --requirepass "__@picker-redis" 
> ```

Do you know if is possible update an container redis with this --requirepass ?

**Comment by yosifkit** [comment]
>Do you know if is possible update an container redis with this --requirepass ?

It might be technically possible but I don't know of a container runtime that will restart a container with a new `CMD`.

With `docker run`, you need to stop and remove the old container and then start a new one with the new argument. Many tools like kubernetes or compose do this when you apply updated yaml config and then it deploys updated containers (they remove the old containers and replace them with new containers with the updated runtime configuration).  Be sure to use a `volume` (or equivalent) for any important on-disk save state to have the new container able to pick up where the other stopped.

**Comment by wget** [comment]
For those wanting a syntax à-la Docker Compose v2, here you are:
```
  nextcloud-prod-redis:
    image: redis:7-alpine
    container_name: nextcloud-prod-redis
    hostname: nextcloud-prod-redis
    environment:
      - REDIS_PASSWORD=<cf. your password manager>
    volumes:
      - "/srv/cloud.example.org/data/redis:/data"
    networks:
      - nextcloud-prod-network
    command: /bin/sh -c 'redis-server --appendonly yes --requirepass $${REDIS_PASSWORD}'
    restart: always
```

The trick here was to double the `$` character in order to avoid Docker Compose from interpreting it.

**Comment by hahuaz** [comment]
For docker-compose.yml leave the username empty in the Redis URL.
  ```
redis:
    image: redis:latest
    container_name: redis
    command: /bin/sh -c "redis-server --requirepass redis"
    ports:
      - 6379:6379
  express:
    stdin_open: true
    environment:
      - REDIS_URL=redis://:redis@redis:6379 # {service}://{username}:{password}@{host}:{port}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-app
    depends_on:
      - redis
    ports:
      - "3000:3000"
    volumes:
      - ./:/app # enable reloading
```
