### ISSUE TITLE
FYI: Connection refused when using a custom config file

### ISSUE THREAD

**Issue by dimitar-nikovski** [docker-library/redis#181]
When loading a custom config in with docker compose 

```
version: '3'
services:
  web:
    build: .
    container_name: node-app
    ports:
      - '8080:80'
    depends_on:
      - redis
    networks:
      - redis-net
    environment:
      # for usage in node client when configuring host connection from base container
      - REDIS_HOST=redis
  redis:
    image: 'redis:alpine'
    container_name: myapp-redis
    ports:
      - '6379:6379'
    networks:
      - redis-net
    command: redis-server /usr/local/etc/redis/redis.conf
    # command: /usr/local/etc/redis/redis.conf
    volumes:
      # map persistency to the host
      - /var/lib/redis:/data
      # mount custom config
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      # mount the redisearch module
      - ./redis/redisearch.so:/usr/lib/redis/modules/redisearch.so
networks:
  redis-net:
````
redis.conf based on the config file in the redis repository
```
... other changes in the config
loadmodule /usr/lib/redis/modules/redisearch.so
```
I falsely assumed that the default config applied to the image is the config from the git repo, therefore I couldn't understand why my adding my config with bind 127.0.0.1 caused the connection to be dropped at redis:6379, not realizing that the defaults are instead:

- no binding (defaults to 0.0.0.0)
- protected mode turned off

therefore in any custom config, these defaults need to be reflected to be consistent with the default settings and to allow access to redis from the other containers in the composition.

Just thought this might help someone else in future.
