### ISSUE TITLE
Warning Transparent Huge Pages

### ISSUE THREAD

**Issue by privateOmega** [docker-library/redis#184]
> WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.

I have included redis in my docker compose file with the following settings.
```
    image: redis
    ports:
      - "6379"
    networks:
      - meraki-network
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
```
What can be done to solve this? I am concerned about latency and memory usage issues stated in the warning.
