### ISSUE TITLE
What is the rationale for not running the container as the defined "redis" user

### ISSUE THREAD

**Issue by nabadger** [docker-library/redis#189]
Hi,

Are there good use-cases as to why the container does not start as the `redis` user? I can see it starts as `root`, then drops down to `redis` via `gosu`.

We know best practise is to not run containers as root, so not sure why we need the extra `gosu` step here to drop the privileges (post starting the container).

Many security conscious companies don't allow root containers to run (blocked at start time), so this forces them to extend this image and set `USER redis` in the `Dockerfile`.

Thanks

**Comment by yosifkit** [comment]
We start as root to make it easy for users to bind mount a local directory for storage without having to think about permissions (like `docker run -d -v /home/myuser/redis-data:/data --name myred redis`):
https://github.com/docker-library/redis/blob/dcc0a2a343ce499b78ca617987e8621e7d31515b/5.0/docker-entrypoint.sh#L12

If you don't need this functionality, then the image should run fine as whatever user you want to run it as. Most systems should allow setting a `user` at runtime without needing to build a new image (like `docker run --user` or `user:` in compose.yml).

**Comment by jfrabetti** [comment]
I know this issue is closed, but how would you specify the user for a deployment (not entire policy) on Kubernetes?  Is the best way to rebuild Redis?   It would be useful to have an image that does not run as root for security reasons.

**Comment by tianon** [comment]
I believe https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod is the appropriate documentation for Kubernetes.

**Comment by wglambert** [comment]
Verifying the Kubernetes example for running as non-root in a deployment: 

`$ kubectl create deploy redis --image=redis --dry-run -o yaml > redis.yaml`

Generated `redis.yaml` with the `securityContext:` added:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - image: redis
        name: redis
        resources: {}
status: {}
```

```console
$ kubectl create -f redis.yaml 
deployment.apps/redis created

$ kubectl exec -it redis-8cddc59b9-hqg64 bash
I have no name!@redis-8cddc59b9-hqg64:/data$ id -u && id -g
1000
1000
```
