### ISSUE TITLE
Data is saved when save is off

### ISSUE THREAD

**Issue by karpotkin** [docker-library/redis#198]
I did everything as stated in the documentation. Turned off data saving, but from time to time redis tries to save data. Since there is nowhere to save them, nothing is saved, but all keys are deleted from memory. How to avoid deleting data from memory?

```
9:M 11 Jul 2019 21:09:59.092 * Ready to accept connections
9:M 11 Jul 2019 22:53:15.725 * DB saved on disk
9:M 11 Jul 2019 22:53:17.925 * DB saved on disk
```
docker-compose.yml

```
version: '3'
services:
  redis:
    image: redis
    command: [sh, -c, "rm -f /data/dump.rdb && redis-server --save '' --dbfilename '' --appendonly no --appendfsync no"]
    ports:
      - 6379:6379
    restart: always
```
Redis v=5.0.5
```
docker exec -it a1fa1d8fc54b redis-cli config get save
1) "save"
2) ""
```
