### ISSUE TITLE
Docker compose YML for redis and node-express

### ISSUE THREAD

**Issue by ankitkumarlalan** [docker-library/redis#221]
I'm trying to connect the redis server with the node-application hosted using two container.
Redis server is up and running using it's container but the node-application is unable to start because it can not connect to Redis container.

Here is my docker-compose.yml
```
version: "2.1"
services:
express-nepse-api:
    image: ankitlalan/express-nepse-api
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - redis_data:/data
    networks:
      - redis-net

  redis:
    image: redis:latest
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    hostname: redis
    networks:
      - redis-net
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
networks:
  redis-net:

volumes:
  redis_data:
    driver: local
```

Redis error on the console:
![image](https://user-images.githubusercontent.com/47514573/72881583-214efe80-3d29-11ea-96fd-cb782a445bc2.png)

Container for the redis is running on port 0.0.0.0
![image](https://user-images.githubusercontent.com/47514573/72881693-59eed800-3d29-11ea-9a76-857a9cb1ee14.png)

Using Redis.createserver() in my application:
```
import redisClient from 'redis';
const redis = redisClient.createClient();
```

Please guide for the connection issue.
