### ISSUE TITLE
Permission Denied on RDB file

### ISSUE THREAD

**Issue by leond08** [docker-library/redis#226]
I ' am getting an error on your docker image says "Permission Denied" 

Here is my docker-compose.yml config

```
version: '3'
services:

  #Redis Service
  redisserver:
    image: redis:5.0.6-alpine
    container_name: redisserver
    restart: always
    tty: true
    ports: 
      - "6379:6379"
   working_dir: /data
    volumes:
      - redisdata: /data
      - /etc/localtime:/etc/localtime
    networks:
      - app-network
 

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  redisdata:
    driver: local
```

Here is the error i encounter

Failed opening the RDB file dump.rdb (in server root dir /etc/crontabs) for saving: Permission denied
