### ISSUE TITLE
CRITICAL/MainProcess] Unrecoverable error: ReadOnlyError("You can't write against a read only replica.")

### ISSUE THREAD

**Issue by danielgarcia0694** [docker-library/redis#227]
I have this error with the redis container.

`CRITICAL/MainProcess] Unrecoverable error: ReadOnlyError("You can't write against a read only replica.")`

I use redis and celery to send mail, but after one or two hours the celery container restarts giving this error.

this is my redis configuration in the ycker docker yml

```
redis:
    restart: always
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./docker/prod/redis/my_redis.conf:/usr/local/etc/redis/my_redis.conf
    command:
      - redis-server
```
