### ISSUE TITLE
Issue loading configuration file from volume

### ISSUE THREAD

**Issue by xKumox** [docker-library/redis#230]
I am very new to Docker in general, so if I have not provided a piece of information that would assist in diagnosing the problem feel free to comment and I will add it in asap.

I am running docker desktop on windows using Linux containers. I am specifying the use of Redis in a docker compose file like so:

```
redis:
   image:  ${DOCKER_REGISTRY-}redis:5.0.8
   volumes: 
       - C:/Git/Path/To/RedisConfig/:/config
   command:
       - /config/redis.conf
   ports:
       - 6379:6379
```
Currently my redis.conf file looks like this:

```
#bind 0.0.0.0
#protected-mode yes
#port 6379
#tcp-backlog 511
#timeout 0
#tcp-keepalive 300
#daemonize no
#supervised no
#pidfile /var/run/redis_6379.pid
#loglevel notice
logfile ""
```
which gives the following error when the container spins up

```
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 1
>>> '#bind 0.0.0.0'
Bad directive or wrong number of arguments
```
Here are a few different config file formats I have tried

An empty config config:

```
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 1
>>> ''
Bad directive or wrong number of arguments
```
No comments with one entry:

```
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 1
>>> 'logfile ""'
Bad directive or wrong number of arguments
```
The only thing that has successfully allowed redis to start is if I remove the command from the compose file:

```
redis:
   image:  ${DOCKER_REGISTRY-}redis:5.0.8
   volumes: 
       - C:/Git/Path/To/RedisConfig/:/config
   ports:
       - 6379:6379
```
Other people have faced similar issues but they all seemed related to using config settings which were not supported in the version of Redis they were using, in my case even an empty config does not work.

Has anyone experienced something similar to this? Thanks in advance for any assistance.
