### ISSUE TITLE
Redis docker-compose requirepass AUTH

### ISSUE THREAD

**Issue by pdavis156879** [docker-library/redis#261]
I'm trying to run Redis and Postgres on a local container using docker-compose. Whilst I'm able to access Postgres without a problem, the same cannot be said with Redis: access fails both via CLI and remote connection (in my case, using Go).

**Redis CLI**
If I try to connect using Redis' CLI I am stuck in AUTH, with my access being continuously denied trying any of the elements:
```
AUTH redispass!
AUTH default redispass!
```

**QuickRedis**
I also tried connecting via QuickRedis, and whilst it initially returns the message "Connection established successfully" it then returns "An error occurred. MaxRetriesPerRequestError: Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details." failing to connect.

I would expect the password to be required since I clearly defined it in docker-compose. Has anyone had the same issue?

**Docker-compose**

```
version: '3.9'

services:
  postgres-main:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgrespass!"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data 
    networks:
      - postgres-network
      
  redis-main:
    image: "redis:alpine"
    restart: always
    environment:
      REDIS_PASSWORD: "redispass!"
    ports:
      - 6379:6379
    volumes:
      - redis-data:/var/lib/redis/data
    networks:
      - redis-network
    command: redis-server --requirepass $${REDIS_PASSWORD}

networks: 
  postgres-network:
  redis-network:

volumes:
  postgres-data:
  redis-data:
```

**Redis docker log**

```
1:C 03 Jan 2021 23:38:45.493 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 03 Jan 2021 23:38:45.493 # Redis version=6.0.9, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 03 Jan 2021 23:38:45.493 # Configuration loaded
1:M 03 Jan 2021 23:38:45.495 * Running mode=standalone, port=6379.
1:M 03 Jan 2021 23:38:45.495 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 03 Jan 2021 23:38:45.495 # Server initialized
1:M 03 Jan 2021 23:38:45.495 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 03 Jan 2021 23:38:45.495 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo madvise > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled (set to 'madvise' or 'never').
1:M 03 Jan 2021 23:38:45.497 * Ready to accept connections
1:signal-handler (1609717701) Received SIGTERM scheduling shutdown...
1:M 03 Jan 2021 23:48:21.195 # User requested shutdown...
1:M 03 Jan 2021 23:48:21.195 # Redis is now ready to exit, bye bye...
1:C 04 Jan 2021 21:12:34.654 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 04 Jan 2021 21:12:34.654 # Redis version=6.0.9, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 04 Jan 2021 21:12:34.654 # Configuration loaded
1:M 04 Jan 2021 21:12:34.656 * Running mode=standalone, port=6379.
1:M 04 Jan 2021 21:12:34.656 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 04 Jan 2021 21:12:34.657 # Server initialized
1:M 04 Jan 2021 21:12:34.657 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 04 Jan 2021 21:12:34.657 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo madvise > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled (set to 'madvise' or 'never').
1:M 04 Jan 2021 21:12:34.658 * Ready to accept connections
```
