### ISSUE TITLE
Please implement secret for password

### ISSUE THREAD

**Issue by schklom** [docker-library/redis#268]
The title should be explicit enough: for security reasons, it would be better to use a `secret`.
Secrets don't require `docker swarm`, so why not allow this ?

A docker-compose would look like this:
```
version: "3.8"

services:
  redis:
    image: redis
    environment:
      REDIS_PASS_FILE: /run/secrets/redis_password
    secrets:
      - redis_password
    volumes:
      - /path_to_redis/redis:/data

secrets:
  redis_password:
    file: /path_to_secrets/redis_pass
```

A current hacky workaround is detailed [here](https://github.com/docker-library/redis/issues/46#issuecomment-364761650).
