### ISSUE TITLE
Losing the Redis data after restart docker, please help

### ISSUE THREAD

**Issue by MacMillan13** [docker-library/redis#270]
### Expected behavior

Don't lose Redis data from volume after restart docker.

### Actual behavior
Lose the Redis data after the restart docker.  My docker-compose is 
```
  redis:
    image: redis:latest
    container_name: face_redis
    restart: always
    command:
      - 'redis-server'
      - '--loglevel ${REDIS_LOGLEVEL:-warning}'
      - '--databases 2'
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 10000'
      - '--maxmemory ${REDIS_MAXMEM:-50mb}'
      - '--maxmemory-policy ${REDIS_POLICY:-noeviction}'
      - '--requirepass ${REDIS_PASSWORD}'
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/data:/var/lib/redis
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - internal
 ```

### Steps to reproduce the behavior
Changed volumes, changed Redis image, added commands.

**Output of `docker version`:**

```
Docker version 19.03.6
```
