### ISSUE TITLE
Running on arm

### ISSUE THREAD

**Issue by AuspeXeu** [docker-library/redis#272]
I am currently using the `redis:6.0-alpine` tag to run redis on my raspberry pi. This all works fine. However, when switching to `redis:6.2-alpine`. The container keeps crashing with this error.

```
redis       | 1:C 10 Jun 2037 05:58:32.000 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis       | 1:C 10 Jun 2037 05:58:32.000 # Redis version=6.2.1, bits=32, commit=00000000, modified=0, pid=1, just started
redis       | 1:C 10 Jun 2037 05:58:32.000 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis       | Assertion failed: rc == 0 (monotonic.c: monotonicInit_posix: 149)
redis       | 
redis       | 
redis       | === REDIS BUG REPORT START: Cut & paste starting from here ===
redis       | 1:M 10 Jun 2037 05:38:16.000 # Redis 6.2.1 crashed by signal: 6, si_code: -6
redis       | 1:M 10 Jun 2037 05:38:16.000 # Killed by PID: 1, UID: 999
redis       | 
redis       | ------ INFO OUTPUT ------
redis       | 1:M 10 Jun 2037 04:54:16.000 # Redis 6.2.1 crashed by signal: 11, si_code: 1
redis       | 1:M 10 Jun 2037 04:54:16.000 # Accessing address: 0x14
redis       | 1:M 10 Jun 2037 04:54:16.000 # Killed by PID: 20, UID: 0
```

**Comment by yosifkit** [comment]
Just a hunch, but this seems like https://github.com/moby/moby/issues/40734 (https://github.com/docker-library/redis/issues/269#issuecomment-778448769).

**Comment by ushachar** [comment]
This is caused by a change in Redis - https://github.com/redis/redis/pull/7644
I've notified the relevant folks on that PR.

**Comment by yossigo** [comment]
Looks like this is not directly related to Redis, but a Docker/libseccomp issue that causes `clock_gettime()` to fail. Please see alpinelinux/docker-alpine#135 for a discussion.

**Comment by tianon** [comment]
Indeed, see also https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0#time64_requirements.

You need to update libseccomp on your host to 2.4.2 or newer and Docker to 19.03.9 or newer (see moby/moby#40734). :+1:

**Comment by YuriyTigiev** [comment]
Why only redis has this issue ? 

I'm trying to solve issue a few days. I used a different solutions from internet but the problem still persist.
How can I should the issue?

docker-compose.yml
```
  redis:
    container_name: redis
    image: redis:alpine
    privileged: true
    security_opt:
      - seccomp:unconfined
    networks:
      - default
    ports:
      - 6379:6379
    volumes:
      - ${PWD}/data/redis:/data
      - ${PWD}/redis.conf:/etc/redis.conf
      - ${PWD}/redis.conf:/usr/local/etc/redis/redis.conf
```

Docker version

```
docker -v
Docker version 20.10.14, build a224086
```


```
cat /etc/os-release
NAME="AlmaLinux"
VERSION="8.5 (Arctic Sphynx)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.5 (Arctic Sphynx)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.5"

```


```
uname -r
5.13.0-30-generic

```
