### ISSUE TITLE
Alpine authentication not working

### ISSUE THREAD

**Issue by jeblackburn** [docker-library/redis#276]
Hello,

I've got a docker-compose file like this:
```yaml
services:
  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - '6378:6379'
    volumes:
      - type: bind
        source: ./redis.conf
        target: /usr/local/etc/redis/redis.conf
```
I've attached my redis.conf file, but the relevant parts are these:
`requirepass "theRightPassword"
bind 0.0.0.0
protected-mode yes`

The result I'm expecting: 
`redis-cli -a notTheRightPassword -p 6378` should not connect.
**from the host**: 
`redis-cli -a theRightPassword -p 6378` should connect and PING should PONG
`redis-cli -a incorrectPassword -p 6378` should not connect and PING should raise an error

**from another container**:
`redis-cli -a theRightPassword -p 6379` should connect and PING should PONG
`redis-cli -a incorrectPassword -p 6379` should not connect and PING should raise an error

Actual results from the host:
```console
redis-cli -a theRightPassword -p 6378
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
**_Warning: AUTH failed_** _// this forces an exception in Python_
127.0.0.1:6378> ping
PONG

redis-cli -a incorrectPassword -p 6378
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
Warning: AUTH failed
127.0.0.1:6378> ping
PONG
127.0.0.1:6378>
```

Actual results from another container, given the WRONG password:
```console
# redis-cli -a incorrectPassword -h redis
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
redis:6379> ping
PONG
redis:6379>
```

**Net of all this: Expected results: Authentication checks work correctly when the client is on the host or on another container. Neither case appears to work.**

Thoughts?

Thanks.
[redis conf.txt](https://github.com/docker-library/redis/files/6238071/redis.conf.txt)
