### ISSUE TITLE
assistance running as nonroot user in kubernetes

### ISSUE THREAD

**Issue by emcay** [docker-library/redis#278]
What is the proper procedure for configuring a container to run as a non root user in kubernetes? I have reviewed past issues for this and can't find a clear explanation of what needs to be done. Any help please?

Configuration:
Kubernetes
runAsNonRoot: true
runAsUser: 999
runAsGroup: 999

```
1:C 04 May 2021 20:57:53.386 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 04 May 2021 20:57:53.386 # Redis version=6.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 04 May 2021 20:57:53.386 # Configuration loaded
1:M 04 May 2021 20:57:53.408 # Can't open the append-only file: Permission denied
```

This is very confusing to me because the appendonly.aof file does appear to be owned by redis:redis.

**Comment by wglambert** [comment]
Duplicate of https://github.com/docker-library/redis/issues/189#issuecomment-516130769

`$ kubectl create deploy redis --image=redis --dry-run -o yaml > redis.yaml`

Generated `redis.yaml` with your specific `securityContext:` added:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
      containers:
      - image: redis
        name: redis
        resources: {}
status: {}
```

```console
$ kubectl apply -f redis.yaml
deployment.apps/redis created

$ kubectl exec -it redis-ff79b445b-xbvcb -- bash
redis@redis-ff79b445b-xbvcb:/data$ id -u && id -g
999
999

redis@redis-ff79b445b-xbvcb:/data$ cat /etc/passwd | grep -i redis
redis:x:999:999::/home/redis:/bin/sh

redis@redis-ff79b445b-xbvcb:/data$ exit
exit
[node1 ~]$ kubectl logs redis-ff79b445b-xbvcb
1:C 04 May 2021 22:01:41.690 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 04 May 2021 22:01:41.692 # Redis version=6.2.3, bits=64, commit=00000000, modified=0, pid=1,just started
1:C 04 May 2021 22:01:41.692 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 04 May 2021 22:01:41.694 * monotonic clock: POSIX clock_gettime
1:M 04 May 2021 22:01:41.763 * Running mode=standalone, port=6379.
1:M 04 May 2021 22:01:41.919 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 04 May 2021 22:01:41.931 # Server initialized
1:M 04 May 2021 22:01:41.986 * Ready to accept connections
```
