### ISSUE TITLE
Redis images changes directory

### ISSUE THREAD

**Issue by denef** [docker-library/redis#294]
I am using a very simple docker compose file to start redis:

```
redis:
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data
    image: "redis:6.2.3"
    command: ["redis-server", "--appendonly", "yes"]
```

Once started everything is fine and `config get dir` returns /data.

```
$redis-cli config get dir
1) "dir"
2) "/data"
```

However, after a while of operation, the dir changes, in different ways:

```
$redis-cli config get dir
1) "dir"
2) "/etc"
```

or

```
$redis-cli config get dir
1) "dir"
2) "/tmp"
```

which results in errors like this:

```
# Failed opening the RDB file dump.rdb (in server root dir /etc) for saving: Permission denied
# Background saving error
client_loop: send disconnect: Broken pipe
```

I found some other people reporting about that in 2018 (https://github.com/docker-library/redis/issues/128), and people suspected some hacker attack on the server. In my case, however, Redis is not exposed to the outside and I have no idea why this happens.
