### ISSUE TITLE
Make two passwords available in the default user

### ISSUE THREAD

**Issue by mrojasbb** [docker-library/redis#310]
Hello all. Sorry if this is not the place to put a question related to redis. If this is not the place, can someone guide me where to put it?
I want to know how can I mark/put two passwords as valid to the `default` user.
I've been trying to do something like:

```
 containers:
  - name: {{ .Chart.Name }}
    securityContext:
      {{- toYaml .Values.redis.securityContext | nindent 12 }}
    image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag | default .Chart.AppVersion }}"
    imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
    env:
      - name: REDIS_SECRET1
        valueFrom:
          secretKeyRef:
            name: "container1"
            key: "REDIS_SECRET1"
      - name: REDIS_SECRET2              
        valueFrom:
          secretKeyRef:
            name: "container1"
            key: "REDIS_SECRET2"
    readinessProbe:
      exec:
        command:
        - bash
        - "-c"
        - |
          redis-cli -a $REDIS_SECRET1 ping
      initialDelaySeconds: 5
    resources:
      {{- toYaml .Values.redis.resources | nindent 12 }}
    command: 
    - bash
    - "-c"
    - |
      redis-server --requirepass $REDIS_SECRET1; redis-cli -a $REDIS_SECRET1 acl setuser default ">$(REDIS_SECRET2)"
```
But got no success, Am I not putting the command `redis-cli -a $REDIS_SECRET1 acl setuser default ">$(REDIS_SECRET2)"` in a correct form or does the `--requirepass` is messing with having two valid passwords for the default user?

Thanks a lot!
