### ISSUE TITLE
Failed opening the RDB file crontab (in server root dir /etc) for saving: Permission denied

### ISSUE THREAD

**Issue by simontol** [docker-library/redis#314]
I keep getting this message in logs:
`# Failed opening the RDB file crontab (in server root dir /etc) for saving: Permission denied`
 If I run `redis-cli config set dir "/data"` then I get:
`Background saving terminated with success`

Am I missing something? I run redis from docker-compose:
```
  my-redis:
    image: redis:6.2-alpine
    container_name: my-redis
    network_mode: host
```
