### ISSUE TITLE
Unable to turn protected mode off in docker compose with the latest version

### ISSUE THREAD

**Issue by saikris12** [docker-library/redis#319]
We have been using the redis image for a while now (as part of our stack) but never hit this issue. We always used the latest image version so we suspect some recent push is causing this. Below is the error we started getting from today. 

```
DENIED Redis is running in protected mode because protected mode is enabled and no password is set for the default user. In this mode connections are only accepted from the loopback interface. 
```
Below is our docker compose : 

```
local-redis:
    image: "bitnami/redis:latest"
    hostname: "local-redis"
    container_name: "local-redis"
    ports:
      - "6479:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
```

We have tried overriding the conf file but that has not worked as well. Has something changed in the latest version. Is protected mode enabled by default now? I could not find anything to suggest that in the documentation.
