### ISSUE TITLE
>= 7.0.1 doesn't accept custom arguments in command

### ISSUE THREAD

**Issue by brusch** [docker-library/redis#320]
Using `docker-compose` the following doesn't work anymore: 
```yml
services:
    redis:
        image: redis:alpine
        command: [ redis-server, --maxmemory 128mb, --maxmemory-policy volatile-lru, --save "" ]
```

It used to work with all v6 images as well as `redis:7.0.0-alpine` but starting from `redis:7.0.1-alpine` startup will fail with the following error message: 

```
| *** FATAL CONFIG FILE ERROR (Redis 7.0.1) ***
| Reading the configuration file, at line 2
| >>> 'maxmemory 128mb "--maxmemory-policy volatile-lru"'
| wrong number of arguments
```
