### ISSUE TITLE
7.0.5 FATAL CONFIG FILE ERROR with default redis.conf

### ISSUE THREAD

**Issue by Colonizator1** [docker-library/redis#329]
docker-compose.yml
version: "3.8"
```
services:
    redis-session:
        build: .
        container_name: redis-session
        restart: always
```

Dockerfile
```
FROM redis
COPY redis.conf /usr/local/etc/redis/redis.conf
CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
```

redis.conf was taken from the official repo https://github.com/redis/redis/blob/unstable/redis.conf

the result after "docker-compose up -d"
```
*** FATAL CONFIG FILE ERROR (Redis 7.0.5) ***
Reading the configuration file, at line 415
>>> 'locale-collate ""'
Bad directive or wrong number of arguments
```

I commented the option locale-collate, but seems that it's not the right way :)
