### ISSUE TITLE
Permissions are reset after config write

### ISSUE THREAD

**Issue by defcon84** [docker-library/redis#348]
Every time Redis saves the config to disk, it resets the permissions of the file.
Initial situation:
```
root@dckr03:/srv/docker/redis7# ls -l
-rwxrwxrwx  1 lxd   docker  286 Feb 22 13:07 redis-server-1.conf
```
Then whenever I get a `CONFIG REWRITE executed with success` in the logs, it saves a new config file (via a temp file).
```
root@dckr03:/srv/docker/redis7# ls -l
-rw------- 1 lxd docker 258 Feb 22 13:10 redis-server-1.conf
```
Same happens for the sentinel configs.
It does not happen with redis:4.
Any idea on how to keep the same permissions on the files?

docker-compose config:
```
  redis7-server-1:
    container_name: "redis7-server-1"
    image: redis:7.0.8
    ports:
      - 7379:7379
    volumes:
      - /srv/docker/redis7:/usr/local/etc/redis
    command: redis-server /usr/local/etc/redis/redis-server-1.conf
    restart: unless-stopped
```

redis server config:
```
bind 0.0.0.0
port 7379
protected-mode no

loglevel notice
syslog-enabled yes

# Generated by CONFIG REWRITE
dir "/data"

save 3600 1
save 300 100
save 60 10000
latency-tracking-info-percentiles 50 99 99.9
user default on nopass sanitize-payload ~* &* +@all

replicaof 192.168.5.42 7379
```
