### ISSUE TITLE
Redis 7.0.11 (latest): Fatal Can't initialize Background Jobs

### ISSUE THREAD

**Issue by flaushi** [docker-library/redis#366]
it seems like 7.0.11 was tagged `latest` lately.
I cannot bring up the service, seemingly on all debian buster hosts, still analyzing there.
My setup is fairly standard:
my docker-compose.yml merely states:
```
version: '2'

services:

    redis:
        image: redis:latest
        restart: unless-stopped
```
