### ISSUE TITLE
Redis can't write to disk - I'm out of ideas

### ISSUE THREAD

**Issue by lockheed** [docker-library/redis#380]
I use this docker compose:
```yaml
version: "2.1"
services:
  broker:
    container_name: paperless-redis
    image: docker.io/library/redis:7
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Warsaw
    volumes:
      - /z/docker/_configs/paperless-ngx/redisdata:/data
    networks:
      - paperless-net

  paperless-ngx:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless
    depends_on:
      - broker
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Warsaw
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DATA_DIR: /config
      PAPERLESS_MEDIA_ROOT: /data/media
      PAPERLESS_TIME_ZONE: Europe/Warsaw
      PAPERLESS_URL: https://doks.impactor.one
    volumes:
      - /etc/localtime:/etc/localtime
      - /z/docker/_configs/paperless-ngx:/config
      - /z/data/paperless-data:/data
    restart: unless-stopped
    networks:
      - frontend
      - paperless-net

networks:
  frontend:
    external: true
  paperless-net:
```

When I try to upload document to paperless-ngx, it doesn't save it and complains
```console
[2023-10-11 08:57:59,897] [ERROR] [celery.worker.consumer.consumer] consumer: Cannot connect to redis://broker:6379//: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error..
Trying again in 32.00 seconds... (16/100)
```

because Redis complains:
```console
1:M 11 Oct 2023 08:56:50.156 # Background saving error
1:M 11 Oct 2023 08:56:56.067 * 1 changes in 3600 seconds. Saving...
1:M 11 Oct 2023 08:56:56.067 * Background saving started by pid 26479
26479:C 11 Oct 2023 08:56:56.067 # Failed opening the temp RDB file temp-26479.rdb (in server root dir /data) for saving: Permission denied
1:M 11 Oct 2023 08:56:56.167 # Background saving error
1:M 11 Oct 2023 08:57:02.078 * 1 changes in 3600 seconds. Saving...
1:M 11 Oct 2023 08:57:02.078 * Background saving started by pid 26480
26480:C 11 Oct 2023 08:57:02.078 # Failed opening the temp RDB file temp-26480.rdb (in server root dir /data) for saving: Permission denied
```

All the disk permissions seem to be correct. I am out of ideas.
