### ISSUE TITLE
Connecting through localhost...

### ISSUE THREAD

**Issue by justinmchase** [docker-library/redis#45]
I am on osx and I'm trying to use this container by doing:
```
$ docker run --name redis -p 6379:6379 -d redis
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
1af8a2abcae9        redis               "/entrypoint.sh redis"   3 minutes ago       Up 3 minutes        0.0.0.0:6379->6379/tcp   redis
```
Based on this it seems like the container is running properly, and the key being: `0.0.0.0:6379->6379/tcp`

However when I attempt to connect to the server via `node_redis` with code like this:

```
var redis = require('redis');
var client = redis.createClient(); // localhost:6379
client.on('error', function (err) {
    console.log('Redis Error:', err); // errors here
});
```
I get this error:
```
Redis Error: { [Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379 }
```
I've tried using some other clients, and they all do the same thing. Furthermore, trying to use the linking suggested in the documentation here, this same code when run in that container is also having this error.

What am I missing?

**Comment by yosifkit** [comment]
If you are trying to connect from your Mac, then you will need to hit the IP address of the VM (`docker machine ip default`) on that port.

If you are hitting it from another container, then you need to hit the redis container's IP address.  You can use `docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' redis` to get its IP address or just use a `--link` on a docker run and it will be in an environment variable:  `docker run -it --link my-redis-container:redis --rm redis sh -c 'exec redis-cli -h "$REDIS_PORT_6379_TCP_ADDR" -p "$REDIS_PORT_6379_TCP_PORT"'`.

**Comment by justinmchase** [comment]
Ok that helped and I managed to figure it out with `docker-compose`!

I created a `docker-compose.yml` file:
```
redis:
  image: redis

driver:
  build: .
  links:
    - redis
```

I then changed my script to be:
```
var client = redis.createClient({
	host: 'redis'
});
```

And then I ran it via:
```
$ docker-compose build
$ docker-compose up
```

**Comment by nvcken** [comment]
Hello, @justinmchase 
So the way docker-compose resolves your problem but what is your problem actually ? I don't figure out.
Is magic come from "links" on docker-compose file

**Comment by justinmchase** [comment]
@nvcken 

I'm not sure exactly but I do believe it had to do with the linking like you suggested. Probably its possible since docker-compose figures it out but the settings + command line switches to make it happen were too complex for mere mortals it seems.

**Comment by danielabar** [comment]
I'm also on a Mac (10.11.4). 

Tried using ip address from `docker-machine ip default` instead of `localhost`, connecting to redis from a node app running on my machine (not in another container), but still get the error:

```
Error: Redis connection to 192.168.99.100:6379 failed - connect ECONNREFUSED 192.168.99.100:6379
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)
```

**Comment by yosifkit** [comment]
@danielabar, you'll need to run redis with a `docker run -d -p 6379:6379 redis` so that the port is connected from the container to the docker-machine VM.

**Comment by danielabar** [comment]
I tried that but still connection refused. Turns out for Mac, have to add port forwarding on `default` vm in Virtual Box, as described [here](https://github.com/docker/docker/issues/4007)  (I just added the 6379 mapping manually to verify the concept, didn't try running that script to do a whole bunch at once)

**Comment by nvcken** [comment]
@danielabar which IP you use to connect redis . Notice 127.0.0.1 does not work, use virtual machine IP instead

**Comment by danielabar** [comment]
I tried that but still connection refused. Only thing that worked is adding 6379 port forwarding to `default` vm in Virtual Box, used by docker toolbox on mac. Then can connect using `localhost`.

![image](https://cloud.githubusercontent.com/assets/2428282/14194664/010c77ea-f77f-11e5-919c-02e7746d1e39.png)

**Comment by twothirdscyft** [comment]
This is how I got it to run using redis:2.8 for local development, but I think same should work for redis:3. Basically need to use custom redis.conf and switch networking mode of docker.

  1. Get a redis configuration from http://redis.io/topics/config and save it to `</path/to/conf-folder>/redis.conf`
  2. Comment out `bind` so that it accepts connections from outside
      * If using redis:3 you have to change the protected mode stuff as well I think
  3. `docker run -p "6379:6739" --net="host" -v "</path/to/conf-folder>:/usr/local/etc/redis" redis:2.8 /usr/local/etc/redis/redis.conf`

**Comment by daratha** [comment]
@justinmchase,

var client = redis.createClient({
    host: 'redis'
});

worked for me, thanks

**Comment by ishmeetbindra** [comment]
@justinmchase 
Thanks, this one works.
```var client = redis.createClient({
host: 'redis'
});

```

**Comment by danielcompton** [comment]
On Docker for Mac, you can do this: `bind 127.0.0.1 docker.for.mac.localhost`. You can then connect to `localhost:6379` from your host machine (assuming you've forwarded 6379), and Redis will connect.

**Comment by nathantech2005** [comment]
I had to set this in my docker-compose.yml file. Under environment:

REDIS_URL=redis://redis:6379/0

**Comment by ezzaouia** [comment]
I guess the cross platform solution for this is using docker networking, for instance with docker compose which is well explained here [compose networking](https://docs.docker.com/compose/networking/).

> Networked service-to-service communication use the CONTAINER_PORT

Example:
>
```
version: "3"
services:
  web:
    build: .
    ports:
      - "8000:8000"
  db:
    image: postgres
    ports:
      - "8001:5432"
```

Here **web**’s _application code_ will use postgres://db:**5432**

**Comment by sitompul** [comment]
I still got this issue, [stackoverflow link](https://stackoverflow.com/questions/48555513/redis-connection-to-127-0-0-16379-failed-using-docker)

here is my docker-compose.yml
```
version: '2'
services:
  mongo:
    image: mongo:3.6
    container_name: "backend-mongo"
    ports:
      - "27017:27017"
    volumes:
      - "./data/db:/data/db"
  redis:
    image: redis:4.0.7
    ports:
      - "6379:6379"
    user: redis
  adminmongo:
    container_name: "backend-adminmongo"
    image: "mrvautin/adminmongo"
    ports: 
      - "1234:1234"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    container_name: "backend-elastic"
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  web:
    container_name: "backend-web"
    build: .
    ports:
     - "8888:8888"
    environment:
     - MONGODB_URI=mongodb://mongo:27017/backend
    restart: always
    depends_on: 
     - mongo
     - elasticsearch
     - redis
    volumes:
     - .:/backend
     - /backend/node_modules
volumes:
  esdata1:
    driver: local
networks:
  esnet:
```

I've tried to use these methods below

```
const redisClient = redis.createClient({host: 'redis'});
const redisClient = redis.createClient(6379, '127.0.0.1');
const redisClient = redis.createClient(6379, 'redis');
```

My redis container is running and can be accesed from my redis-cli and other **non-docker node js** app

But it looks like my docker node.js cannot communicate with my docker redis.

Has anyone encountered such issue?

**Comment by emredoganm** [comment]
@justinmchase you saved my life. Thank you so much 👍

**Comment by Epoxboy** [comment]
@yosifkit  just a quick check is your comment on 9 Feb 2016 still valid? meaning no way to connect to another container port from a container which is running on the same host(VM).

thank you!

**Comment by kunokdev** [comment]
@twothirdscyft  Your solutions seems the only one that would work for me. I am using version 4. What other stuff other than `bind` line should I change? 

To inspect me issue further see: https://stackoverflow.com/questions/50958399/while-using-docker-compose-node-application-fails-to-connect-to-redis

**Comment by yosifkit** [comment]
@Epoxboy, You can go from one container to the host exposed port of another container but it would have to be either via the Docker host IP address or the Docker bridge IP address.

Assuming you have this kind of setup:

```yaml
version: "3"
services:
  alpha:
    image: my-web-app
    ports:
      - "8080:80"
  beta:
    image: my-web-app2
    ports:
      - "8081:80"

# And the the Docker host IP address is 10.10.10.10
# and a docker bridge IP of 172.17.17.1
```

Then the alpha container can access beta at `http://beta:80`, or via the exposed port at `http://172.17.17.1:8081` and `http://10.10.10.10:8081`.

**Comment by Epoxboy** [comment]
@yosifkit thank you!

**Comment by asmdk** [comment]
hi guys,
I have the same probles and this solution doesn't work for me, because I use the same code for differents applications, and first of them uses the host 127.0.0.1, and I set up in the code this server, but when I use this code for another app, it doesn't work, and I can't change the host to 'redis' or 172......
Is there some solution for me?

**Comment by asmdk** [comment]
it is funny, after I left the comment, I've found solution here:
https://docs.docker.com/engine/reference/run/

You can use a network mode
`
$ docker run -d --name redis example/redis --bind 127.0.0.1
$ # use the redis container's network stack to access localhost
$ docker run --rm -it --network container:redis example/redis-cli -h 127.0.0.1
`

**Comment by JavaHelper** [comment]
I ran the redis on docker like below 

```
 docker run --name some-redis -d redis
d2ea8a77ba543b3e85020de6bc450e0d50ce9f60e0307e52fd4ae394bd297223
```

What the step to connect to redis-cli and access redis?

**Comment by tao12345666333** [comment]
@JavaHelper  you can try this below:

```sh
docker exec -it d2ea8a77ba543b3e85020de6bc450e0d50ce9f60e0307e52fd4ae394bd297223 redis-cli
```

or  you can use other container, like this:

```sh
docker run --rm -it --net container:d2ea8a77ba543b3e85020de6bc450e0d50ce9f60e0307e52fd4ae394bd297223 redis redis-cli
```

**Comment by nineblu** [comment]
> I'm also on a Mac (10.11.4).
> 
> Tried using ip address from `docker-machine ip default` instead of `localhost`, connecting to redis from a node app running on my machine (not in another container), but still get the error:
> 
> ```
> Error: Redis connection to 192.168.99.100:6379 failed - connect ECONNREFUSED 192.168.99.100:6379
>     at Object.exports._errnoException (util.js:890:11)
>     at exports._exceptionWithHostPort (util.js:913:20)
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)
> ```

thanks, it works for me.

**Comment by nineblu** [comment]
> I tried that but still connection refused. Only thing that worked is adding 6379 port forwarding to `default` vm in Virtual Box, used by docker toolbox on mac. Then can connect using `localhost`.
> 
> ![image](https://cloud.githubusercontent.com/assets/2428282/14194664/010c77ea-f77f-11e5-919c-02e7746d1e39.png)

thanks a lot, it works for me.

**Comment by andigwandi** [comment]
somehow I was using 2.0.0 redis dependecies in my nodejs app (was looking at a udemy lesson). upgrading it from 2.0.0 to 2.8.0 worked like a charm.

Docker-Compose
```
version: '3'
services:
  redis-server:
    image: 'redis'
  node-app:
    build: .
    ports:
      - "4001:8081"
```

package.json
```
{
    "dependencies": {
        "express": "*",
        "redis": "2.8.0"
    },
    "scripts": {
        "start": "node index.js"
    }
}
```
redis client in index.js
```
const client = redis.createClient({
    host: 'redis-server',
    port: 6379
})
```
