### ISSUE TITLE
Set password and other options via ENV variable

### ISSUE THREAD

**Issue by phlegx** [docker-library/redis#46]
It would be awesome if it would be possible to set the Password via an ENV variable. Is this planned any time soon or maybe even already possible?

Of course it would even more awesome when we could set other parameters as well :+1:

**Comment by Starefossen** [comment]
In the mean time you could check out [tutumcloud/redis](https://github.com/tutumcloud/redis).

**Comment by yosifkit** [comment]
We don't supply a config file, so that would be up to you to just `COPY` or mount in a config and set whatever options you need.  Using your own config is described on the [Docker Hub](https://hub.docker.com/_/redis/) or a more direct link to the [source](https://github.com/docker-library/docs/tree/a14eb1274914794dd8cb04473df86a8fbf6b3a3f/redis#additionally-if-you-want-to-use-your-own-redisconf-).

**Comment by oryband** [comment]
@yosifkit copying a config file at build time isn't dynamic. Many scenarios involve creating a config template, passing environment variables and generating a configuration file in the entrypoint. This isn't a good solution.

**Comment by oryband** [comment]
tutumcloud/redis is going to be deprecated soon. This alternative looks interesting: https://github.com/bitnami/bitnami-docker-redis

**Comment by phlegx** [comment]
@oryband That is a nice one, thank you very much! Going to test this out

**Comment by tianon** [comment]
I'm still not sure I'm understanding what the need here for additional complexity is, given that Redis itself supports supplying any of the configuration file options directly via the command-line, which I've just verified:
```console
$ docker run --name some-redis -d redis redis-server --requirepass foobared
896132042afb124aae06ea855e02da2a211bd0540a862f1d785b586a3bbc4479
$ docker run -it --link some-redis:redis --rm redis redis-cli -h redis -p 6379
redis:6379> AUTH test
(error) ERR invalid password
redis:6379> AUTH foobared
OK
redis:6379> 
```

This could be abstracted to an environment variable trivially via something like:
```console
$ docker run --name some-redis -d -e REDIS_PASSWORD=foobared redis sh -c 'exec redis-server --requirepass "$REDIS_PASSWORD"'
```

**Comment by tianon** [comment]
Additionally to bake an image that supports that usage:
```Dockerfile
FROM redis

ENV REDIS_PASSWORD default-password

CMD ["sh", "-c", "exec redis-server --requirepass \"$REDIS_PASSWORD\""]
```

Combine that with automated builds (https://docs.docker.com/docker-hub/builds/) and repository links (https://docs.docker.com/docker-hub/builds/#repository-links) and it's reasonably easy to have an up-to-date image built `FROM` this one which supports supplying `REDIS_PASSWORD` for setting a password, if that's necessary.

**Comment by josegonzalez** [comment]
Just for a bit of context, [Dokku](https://github.com/dokku) integrates with the "official" images provided by docker to give developers access to various popular datastores. We use internal networking by default - safer on infra where there isn't private networking, like DigitalOcean - requiring that users manually expose the datastores for remote access.

In the case where a user wants to expose a service publicly, even a bit of protection is nice, and where possible we default to requiring a password for a datastore anyhow. Redis is the only one where we can't do that without:

- Modifying a file on disk (eh)
- Setting the password in the clear for the docker run command (ew)

It would be nice if we could set an environment variable for the password, as then we can easily integrate password protection and provide our users a modicum of security.

See https://github.com/dokku/dokku-redis/issues/58 for (a lot less) detail.

**Comment by yosifkit** [comment]
@josegonzalez, It would not have to be in the clear on the command line. :smile: 

```
$ # export your password env or run some script that exports the password to $SUPER_PASS
$ docker run --name some-redis -d redis redis-server --requirepass "$SUPER_PASS"
$ # bash will evaluate the env var before it is passed to docker

$ # which would be basically the same as if we implemented the desired env
$ docker run --name some-redis -d -e REDIS_PASSWORD="$SUPER_PASS" redis redis-server
```

**Comment by josegonzalez** [comment]
Wouldn't that show up in the output of docker inspect? I suppose providing an env file would be the same, but at least it wouldn't be in the command inspect output.

**Comment by tianon** [comment]
The "--env-file" feature is client-side-only; it parses the file and passes
the relevant "environment" options directly, so they'll still appear in the
"docker inspect" output.

**Comment by anthonyrisinger** [comment]
FWIW, both the `postgres` and `mysql` images support doing several common initialization tasks via `ENV`.

I think this makes for a nicer evaluation experience. It's simple to plug a `redis` container to an existing app this way because the container can configure itself to whatever the app expects. I'm trying to do this right now to localize our platform, and am working around the lack of `ENV` configuration in pretty much the ways stated above (intercept `ENTRYPOINT` or `COMMAND`), but it's a chore nonetheless.

When I first look at an available docker image, one of the next things I do is look at how flexible it is and what it can do via `ENV`, since that's the primary container config mechanism. If you require the user to extend your image and publish their own variant to some registry, for even basic/simple configuration, I feel the bar was raised quite a bit without any pragmatic benefit.

I've seen images accept an entire config via `ENV`, or use some convention to translate `ENV` keys into config assignments. Neither is too difficult to do in a custom `ENTRYPOINT`, and neither adds any overhead aside from a few extra bytes. I think expecting people to unconditionally extend the `redis` image for anything beyond toy usage results in a weaker DX/developer-experience.

**Comment by yosifkit** [comment]
@anthonyrisinger, `postgres` and `mysql` both require the server to be running to create users, which is why they have environment variables. None of their configuration is done via env vars and both databases can take most settings that could be set via a config file, through a flag:

```console
$ # postgres
$ docker run --name pg -d postgres -c max_connections=200 -c shared_buffers=1GB -c effective_cache_size=3GB -c work_mem=5242kB -c maintenance_work_mem=256MB -c min_wal_size=1GB -c max_wal_size=2GB -c checkpoint_completion_target=0.7 -c wal_buffers=16MB -c default_statistics_target=100

$ # mysql
$ docker run --name sql -d -e MYSQL_ROOT_PASSWORD=my-secret-pw mysql --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
```
Redis is basically the same but allows all of its [config via flags](https://redis.io/topics/config#passing-arguments-via-the-command-line), including password.

```console
$ docker run --name red -d redis --slaveof 10.0.0.2 6379 --requirepass secret
```

Doing the same via docker-compose:
```yaml
version: "2"

services:
  postgres:
    image: postgres
    command: >
      -c max_connections=200
      -c shared_buffers=1GB
      -c effective_cache_size=3GB
      -c work_mem=5242kB
      -c maintenance_work_mem=256MB
      -c min_wal_size=1GB
      -c max_wal_size=2GB
      -c checkpoint_completion_target=0.7
      -c wal_buffers=16MB
      -c default_statistics_target=100
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
  redis:
    image: redis
    command: >
     --slaveof 10.0.0.2 6379
     --requirepass secret 
```
How are flags to `CMD` any different than setting environment variables or even different from the mysql and postgres images?

**Comment by anthonyrisinger** [comment]
@yosifkit I acknowledge you can get there with `COMMAND`, and that's a fair point about the other databases requiring online configuration. `mysql` does allow other config, like `MYSQL_ONETIME_PASSWORD` or `*_FILE`, and `postgres` gets fancy with `POSTGRES_INITDB_XLOGDIR`. To some degree this whole thing is probably subjective and preference-driven, stemming from the dichotomy of containers being both CLI-like and appliance-like.

I like the declarative aspect of `ENV`. I am instructing this black box thinger what I need from it, as opposed to executing a tool/binary and knowing its rules and idiosyncrasies. I also like that it's key/value, which makes it straightforward to CRUD individual items from `docker inspect` or consume/generate from shell.

I might be old-fashioned or in the minority here, I'm not sure. `ENV` was always the way the config a system/OS container, since the way before time, long long ago! Hard to pass args to good ol' `init` after all. Docker became ubiquitous and lowered the bar to the point images now successfully compete directly with native binaries, which I think is super. Nonetheless, I generally still find `ENV` more pleasant to use and mechanically process on the daily, especially for apps I don't know very well or am just trying to get usable for whatever reason.

What say you? (whynotboth)?

**Comment by christrewin** [comment]
Would there be a way to use Docker secrets to read from /run/secrets/redis-pass and set the redis --requirepass flag?

For example:

On a swarm manager set the redis-pass, then use docker stack deploy -c docker-compose-prod.yml appname

```
version: '3.1'

secrets:
    redis-pass:
        external: true

redis:
    build: ./redis
    image: redis:3.2.9
    networks:
        - frontend
    ports:
        - "6379"
    deploy:
        replicas: 2
        update_config:
            parallelism: 2
            delay: 10s
        restart_policy:
            condition: on-failure
    secrets:
        - redis-pass:
    environment:
        - REDIS_PASS_FILE: /run/secrets/redis-pass
```

**Comment by amq** [comment]
We need some more love for Redis :) MariaDB has this since almost a year: https://github.com/docker-library/mariadb/commit/6452a881b90283f46c88925b08c2d580a49a27cc
@tianon

**Comment by yosifkit** [comment]
I am still against adding env vars for config since a) it is easy to add to `COMMAND` or `docker run` and b) adding just one will open the avalanche for all of them and we don't want to maintain a list of all possible redis config options for each version of redis.  

@amq, here is a solution for using a secret with the cli flag. I did it with a volume, but a secret should be the same by swapping out the volume and adding in the yaml for the secret.

```yaml
version: '3.1'

services:
  redis:
    image: redis:4.0.2
    volumes:
      - './secret:/run/secrets/redis-pass'
    environment:
        REDIS_PASS_FILE: /run/secrets/redis-pass
    command: [
      "bash", "-c",
      '
       docker-entrypoint.sh
       --requirepass "$$(cat $$REDIS_PASS_FILE)"
      '
    ]
```

**Comment by amq** [comment]
@yosifkit I'm only asking for the secret support of the password env var. I agree that using secrets for all env configuration is unnecessary.

**Comment by MariaWf** [comment]
@yosifkit  thank you ,great!

```
redis:
    image: redis
    ports:
      - "6379:6379"
    environment:
        REDIS_PASS_FILE: /run/secrets/redis-password
    command: [
      "bash", "-c",
      '
       docker-entrypoint.sh
       --requirepass "$$(cat $$REDIS_PASS_FILE)"
      '
    ]
    volumes:
      - ./db/redis/etc/redis.conf:/usr/local/etc/redis/redis.conf 
      - ./db/redis/data:/data 
      - ./db/redis/etc/redis-password:/run/secrets/redis-password 
    networks:
      - code-network 
```

**Comment by feluxe** [comment]
In case anyone wonders if tianon's solution would work with **kubernetes** *secrets* as well... It works. I just tested it. You can use a password for redis from a secret like this:

`redis-dockerfile`:
```
FROM redis

CMD ["sh", "-c", "exec redis-server --requirepass \"$REDIS_PASSWORD\""]

```

`redis-secret.yaml`:
```
...
metadata:
  name: my-secret
...
data:
  redis-password: my_redis_pw_string
```

`redis-deployment.yaml`:
```
        ...
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: redis-password

```

**Comment by t3ran13** [comment]
i think the best way for docker-compose set .env 
https://docs.docker.com/compose/environment-variables/#the-env-file

```
$ cat .env
PSWD=123

$ cat docker-compose.yml
version: "3"
services:
  redis:
    image: redis:3.2
    ports:
      - "6379:6379"
    command: [
          "bash", "-c",
          '
           docker-entrypoint.sh
           --requirepass ${REDIS_PSWD}
          '
    ]
```

check with 
```
docker-compose config
```

**Comment by adampl** [comment]
Inspired by @yosifkit I've ended up with something more robust:

```
services:
  redis:
    image: redis
    environment:
      REDIS_PASS_FILE: /run/secrets/redis-pass
    command: bash -c '[ "$$REDIS_PASS_FILE" ] &&
      ( cat "$$REDIS_PASS_FILE" | xargs -0 redis-server --requirepass ) || redis-server'
```
This allows you to use all characters in the secret file (except _null_), or to not set the password when the environment variable is empty or unset (useful for development).

**Comment by davesmits** [comment]
so i now what to use redis on my kubernetes cluster and first need to build my own image to be able to get the password in it via kubernetes secrets? really? this should be in the box by default

**Comment by AnatolyRugalev** [comment]
@davesmits there is possibility to override command in pod manifest, see https://kubernetes.io/docs/concepts/workloads/pods/pod-overview/

You could inject secret to environment variable and then pass it to `command` option

**Comment by jeff1985** [comment]
Providing a password should be easy and documented directly in the README! Otherwise you risk thousands of lazy sysadmins exposing their images to the wild without any protection. 

Please add this feature soon!

**Comment by ermik** [comment]
@AnatolyRugalev isn't it the case that in k8s it is preferred to use `args` key for command args? I think the config should be as follows:
```yaml
containers:
- name: redis
  image: my-custom-redis-image
  command: ["redis-server"]
  args: ["/etc/redis.conf", "--requirepass", "$(REDIS_PASSWORD)"]
  env:
  - name: REDIS_PASSWORD
    valueFrom:
      secretKeyRef:
        name: redis-password
        key: password
```
