### ISSUE TITLE
save option not recognized

### ISSUE THREAD

**Issue by mrmunch** [docker-library/redis#87]
When I start `redis:3.2.6-alpine` Container with command `redis-server`, no save-option are set: `CONFIG GET *` returns me an empty string after "save" (line 130). But as I understand, via default the should be a save option set: https://raw.githubusercontent.com/antirez/redis/3.0/redis.conf
Nevertheless, I tried to start the container with command `redis-server --save "900 1 300 10"` but same result.
I had to create my own redis docker image and add my custom redis.conf to get it to work, but it should also be possible with command options.

**Comment by tianon** [comment]
I can't seem to reproduce :confused: 
```console
$ docker pull redis:3.2-alpine
3.2-alpine: Pulling from library/redis

Digest: sha256:a06a61747e4a7b46788e2813b21ea6b06386df8e238e56f51f8793adb48f0a8b
Status: Image is up to date for redis:3.2-alpine
$ docker run -dit --name my-redis redis:3.2-alpine
1520e01b50dbea6253da2795b0919666bfc74d2f5ddb211d96579b086d34611b
$ docker exec -it my-redis redis-cli
127.0.0.1:6379> CONFIG GET SAVE
1) "save"
2) "3600 1 300 100 60 10000"
127.0.0.1:6379> 
```

**Comment by ealebed** [comment]
I had same issue:

```
Pulling redis (redis:4.0-alpine)...
4.0-alpine: Pulling from library/redis
Digest: sha256:0153c5db97e5852b25c5c4715cf88cff9d9dfd8fef5c4c81df8b4dd1a984abc7
Status: Image is up to date for redis:4.0-alpine
```

Run redis container from docker-compose.yml:
```
...
  redis:
    container_name: redis
    image: redis:4.0-alpine
    command:
      - 'redis-server'
      - '--loglevel ${REDIS_LOGLEVEL:-warning}'
      - '--databases 2'
      - '--maxmemory ${REDIS_MAXMEM:-50mb}'
      - '--maxmemory-policy ${REDIS_POLICY:-noeviction}'
      - '--requirepass ${REDIS_PASS}'
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
...
```

```
$ docker exec -it redis redis-cli -a password config get save
1) "save"
2) ""
```

Than I modify my docker-compose.yml to this:
```
...
  redis:
    container_name: redis
    image: redis:4.0-alpine
    command:
      - 'redis-server'
      - '--loglevel ${REDIS_LOGLEVEL:-warning}'
      - '--databases 2'
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 10000'
      - '--maxmemory ${REDIS_MAXMEM:-50mb}'
      - '--maxmemory-policy ${REDIS_POLICY:-noeviction}'
      - '--requirepass ${REDIS_PASS}'
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
...
```

Run redis again, and now it works fine:

```
$ docker exec -it redis redis-cli -a password config get save
1) "save"
2) "900 1 300 10 60 10000"
```
