### ISSUE TITLE
Eventually getting MISCONF errors even with volume specified using docker-compose

### ISSUE THREAD

**Issue by beaugunderson** [docker-library/redis#93]
I start getting these errors soon after running the container:

> MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.

Here's the relevant bit from my `docker-compose.yml`:

```yaml
version: '3'

services:
  redis:
    command: redis-server --appendonly yes
    container_name: task-conveyor-redis
    image: redis:3.2-alpine
    volumes:
      - task-conveyor-data:/data

volumes:
  task-conveyor-data:
```

I'm using Docker `17.05.0-ce-mac11 (17656)`.

I tried following the advice in [this StackOverflow answer](http://stackoverflow.com/a/35290309/60371) to no avail.
